// src/services/api.js

const API_BASE_URL = 'http://localhost:8081';

/**
 * Uploads a CSV configuration to the orchestrator to begin the full pipeline.
 * Returns the project_dir and a success message.
 */
export async function startFullPipeline(file, targetColumn = "") {
    // Post the file to the FastAPI backend to be saved locally
    const formData = new FormData();
    formData.append("file", file);

    const uploadRes = await fetch(`${API_BASE_URL}/upload`, {
        method: "POST",
        body: formData
    });

    if (!uploadRes.ok) {
        const errData = await uploadRes.json();
        throw new Error(errData.error || "Failed to upload dataset");
    }

    const uploadData = await uploadRes.json();

    // Return the absolute path as generated by the backend
    return {
        csv_path: uploadData.csv_path,
        output_folder: uploadData.output_folder,
        run_id: uploadData.run_id,
        target_column: targetColumn,
        status: 'ready_to_stream'
    };
}

/**
 * Creates an EventSource to stream logs from a specific agent.
 */
export function streamAgentLogs(agentName, payload, onLog, onResult, onError, onDone) {
    // Convert payload to query params or POST body. 
    // EventSource only supports GET requests natively.
    // We need to use a custom polyfill or fetch-based SSE if sending JSON POST bodies.

    // Since FastAPI SSE endpoints usually expect POST for A2ATask bodies,
    // we'll implement a custom fetch-based SSE reader.

    const controller = new AbortController();

    const startStream = async () => {
        try {
            const response = await fetch(`${API_BASE_URL}/a2a/${agentName}/stream`, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'Accept': 'text/event-stream',
                },
                body: JSON.stringify({
                    task_id: `ui_task_${Date.now()}`,
                    sender: 'ui_dashboard',
                    recipient: agentName,
                    capability: `${agentName}_generation`,
                    input: payload
                }),
                signal: controller.signal
            });

            if (!response.ok) {
                throw new Error(`HTTP Error: ${response.status}`);
            }

            const reader = response.body.getReader();
            const decoder = new TextDecoder('utf-8');

            let buffer = '';

            while (true) {
                const { done, value } = await reader.read();
                if (done) break;

                buffer += decoder.decode(value, { stream: true });

                const lines = buffer.split('\n\n');
                buffer = lines.pop() || ''; // Keep incomplete part in buffer

                for (const line of lines) {
                    if (line.startsWith('data: ')) {
                        try {
                            const dataStr = line.substring(6);
                            if (dataStr.trim() === '') continue;

                            const event = JSON.parse(dataStr);

                            if (event.type === 'log') {
                                onLog(event.message);
                            } else if (event.type === 'result') {
                                onResult(event.data);
                            } else if (event.type === 'error') {
                                onError(event.message);
                            } else if (event.type === 'done') {
                                onDone();
                            }
                        } catch (err) {
                            console.warn("Error parsing SSE JSON:", err, line);
                        }
                    }
                }
            }
        } catch (err) {
            if (err.name !== 'AbortError') {
                onError(err.message || 'Connection failed');
            }
        }
    };

    startStream();

    // Return abort function so component can unmount safely
    return () => controller.abort();
}
